// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/df0018f90db5b89d3f791cd71f98c6bf44a30f23/gsap/index.d.ts
declare module 'gsap' {
// Type definitions for GSAP v1.19
// Project: http://greensock.com/
// Definitions by: VILIC VANE <https://vilic.github.io/>
// Definitions: https://github.com/DefinitelyTyped/DefinitelyTyped


export = TweenLite;
}
